# NumPy Basic

## NumPy (Numerical Python) is a Python library used for numerical computations.

In [1]:
# mporting numpy

import numpy as np

### Functions to create NumPy arrays

#### 1 D array

In [2]:
# creating numpy array
arr = np.array([1,2,3,4,5])
print(arr)

# checking type of this array
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### 2 D array

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


#### 3 D array

In [4]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### dtype

In [5]:
# making array of float data type
d = np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [6]:
# making array of bool data type
e = np.array([1,2,3,4,5],dtype=bool)
print(e)

[ True  True  True  True  True]


#### np.arange()

In [7]:
# syntax -> np.arange(start,end,skip)

arr = np.arange(1,6,2)
print(arr)

[1 3 5]


#### reshape

In [8]:
# reshape converts the shape of arrays
# syntax -> .rehsape(rows, cols)
arr = np.arange(1,11).reshape(5,2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


#### np.ones()

In [9]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#### np.zeros()

In [10]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### np.random()

In [11]:
# .random() used to create arrays with random values

arr = np.random.random((3,4))
print(arr)

[[0.4019148  0.01718519 0.13749372 0.90230215]
 [0.33326659 0.81814728 0.05934393 0.90124532]
 [0.29765977 0.38694949 0.62400793 0.5573327 ]]


#### np.linspace

In [12]:
# linspace generates ponts on equal distance within a given range 
# syntax -> np.linspace(lower range, upper range, no. of items that you want to generate)

arr = np.linspace(10,20,10)
print(arr)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


#### np.identity

In [13]:
# identity matrix -> who's diagonally items are 1

arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [15]:
# creating arrays 

a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


#### ndim -> means no. of dimensions

In [16]:
# syntax -> arrayName.ndim

# checking dimension of array a1
print(a1.ndim)

# a2
print(a2.ndim)

# a3
print(a3.ndim)

1
2
3


#### .shape

##### .shape is used to know size of the array in each dimension

In [17]:
# a1
print(a1.shape)

# a2
print(a2.shape)

# a3
print(a3.shape)


(10,)
(3, 4)
(2, 2, 2)


### .size 

#### .size return the total number of elements in an array,

In [18]:
# a1
print(a1.size)

# a2
print(a2.size)

# a3
print(a3.size)

10
12
8


### .itemsize

#### .itemsize tell how much size each item is occupying in the memory 

In [19]:
# a1
print(a1.itemsize)

# a2
print(a2.itemsize)

# a3
print(a3.itemsize)

8
8
8


### Changing Datatypes

#### .astype

In [20]:
# displaying original 
print(type(a3))

# converting into int32
a3.astype(np.int32)

<class 'numpy.ndarray'>


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

#### Scalar Operations

In [ ]:
# in scalar operations we operate with single scalar (value) on the numpy array

# Arithmetic operations

# multiplying with scalar

# multiplying array a1 with 2
print(a1 * 2)

# multiplying array a2 with 2
print(a2 * 2)

# multiplying array a3 with 2
print(a3 *2)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]]
[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]


In [27]:
# adding with scalar

# a1
print(a1 +5)

# a2
print(a2 +5)

# a3
print(a3 +5)

[ 5  6  7  8  9 10 11 12 13 14]
[[ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [31]:
# Relationsl Operations

# a2
a2 > 5 # now this will work item wise and check that each item in a2 is greater then 5 or not, if yes then print true otherwise false

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
# now let's check if the elements in a1 is  == 4
a1 == 4

array([False, False, False, False,  True, False, False, False, False,
       False])

#### Vector Operations

In [42]:
# when we do operations on two numpy arrays, this is called vector operations

# adding a1 and a2
a2 + a2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

### Array Functions

In [55]:
# creating random array 

b1 = np.random.random((3,3))
b1 = np.round(b1*100)  # .round -> number ko nearest (sabse paas wali) simple value pe le jana
b1


array([[88., 20., 67.],
       [29., 22., 24.],
       [79., 20., 73.]])

#### max

In [57]:
# max gives the maximum value in the array
np.max(b1)

np.float64(88.0)

### min

In [58]:
# min gives the minimum value in the array
np.min(b1)

np.float64(20.0)

### sum

In [59]:
# sum function is used to find the sum of the entire array
np.sum(b1)

np.float64(422.0)

#### prod

In [64]:
# prod (product) gives the product (multiplication) of all the elememnts present in the array
np.prod(b1)

np.float64(208256870553600.0)

In [68]:
# now if we want to find the minumum / maximum of each row / columns -> we use axis

# in axis
# 0 -> cols
# 1 -> rows 


np.min(b1,axis=0)

array([29., 20., 24.])

### Statistical Operations

#### mean

In [70]:
# mean of entire array
np.mean(b1)


# if we want to find the mean of cols / rows we can use axis
np.mean(b1,axis=0)

array([65.33333333, 20.66666667, 54.66666667])

#### median

In [72]:
# median gives us the center value of array
np.median(b1)

np.float64(29.0)

#### std

In [73]:
# std (standard deviation)
np.std(b1)

np.float64(27.318876032046433)

#### var

In [74]:
# variance
np.var(b1)

np.float64(746.320987654321)

### Trigonometric functions

In [76]:
# sin

np.sign(b1)

# similarly you can use cos, tan etc

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### dot product

In [79]:
# creating arrays

b2 = np.arange(12).reshape(3,4) # 3 rows and 4 cols
b3 = np.arange(12,24).reshape(4,3) # 4 rows and 3 cols

# basic rule for finding the dot product is (column of 1st should match the row of 2nd)

np.dot(b2,b3) # result will be in 3 X 3 matrix

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

#### logs and exponents

In [81]:
# caluclating log
np.log(b2)

/var/folders/9b/pfvkrsns3sx2_k1ncj82klqm0000gn/T/ipykernel_2038/2234619865.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(b2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [83]:
# calculting ecponents using exp function
np.exp(b2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

#### round, floor and ceil

In [87]:
# creating array

# round ka use numbers ko nearest value (usually integer ya specified decimal place) tak le jane ke liye hota hai. 

# in simple words -> it rounds off to the nearest integer value
np.round(np.random.random((2*3)) * 100)

array([52., 92., 97., 53., 55., 47.])

In [88]:
# floor
# means downward rounding (peeche ki trf le k jata h values ko)

np.floor(np.random.random((2,3))*100)

array([[25., 96., 29.],
       [90., 76., 29.]])

In [ ]:
# ceil
# ceil means upward rounding (aage wale interger p le k jata h values ko)
np.ceil(np.random.random((2,3))*100)

array([[51., 17., 96.],
       [ 9., 12., 16.]])

### Indexing and Slicing