# NumPy Basic

## NumPy (Numerical Python) is a Python library used for numerical computations.

In [2]:
# mporting numpy

import numpy as np

### Functions to create NumPy arrays

#### 1 D array

In [3]:
# creating numpy array
arr = np.array([1,2,3,4,5])
print(arr)

# checking type of this array
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### 2 D array

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


#### 3 D array

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### dtype

In [20]:
# making array of float data type
d = np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [21]:
# making array of bool data type
e = np.array([1,2,3,4,5],dtype=bool)
print(e)

[ True  True  True  True  True]


#### np.arange()

In [29]:
# syntax -> np.arange(start,end,skip)

arr = np.arange(1,6,2)
print(arr)

[1 3 5]


#### reshape

In [32]:
# reshape converts the shape of arrays
# syntax -> .rehsape(rows, cols)
arr = np.arange(1,11).reshape(5,2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


#### np.ones()

In [34]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#### np.zeros()

In [35]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### np.random()

In [41]:
# .random() used to create arrays with random values

arr = np.random.random((3,4))
print(arr)

[[0.21821538 0.58333097 0.76094843 0.08224479]
 [0.83498225 0.17353949 0.24162845 0.38222779]
 [0.29689649 0.5728319  0.10355063 0.33203539]]


#### np.linspace

In [43]:
# linspace generates ponts on equal distance within a given range 
# syntax -> np.linspace(lower range, upper range, no. of items that you want to generate)

arr = np.linspace(10,20,10)
print(arr)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


#### np.identity

In [45]:
# identity matrix -> who's diagonally items are 1

arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [7]:
# creating arrays 

a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [8]:
#### ndim -> means no. of dimensions

In [14]:
# syntax -> arrayName.ndim

# checking dimension of array a1
print(a1.ndim)

# a2
print(a2.ndim)

# a3
print(a3.ndim)

1
2
3


#### .shape

##### .shape is used to know size of the array in each dimension

In [18]:
# a1
print(a1.shape)

# a2
print(a2.shape)

# a3
print(a3.shape)


(10,)
(3, 4)
(2, 2, 2)


### .size 

#### .size return the total number of elements in an array,

In [21]:
# a1
print(a1.size)

# a2
print(a2.size)

# a3
print(a3.size)

10
12
8


### .itemsize

#### .itemsize tell how much size each item is occupying in the memory 

In [23]:
# a1
print(a1.itemsize)

# a2
print(a2.itemsize)

# a3
print(a3.itemsize)

8
8
8
